
SELECT YEAR_REPORT, MEMBER_CASUAL, RIDE_MORE_45_MINUTES, RIDEABLE_TYPE, SUM(TRIPS) TRIPS, SUM(INCOME_PER_USE) INCOME_PER_USE
FROM INCOME_TABLE_PER_DAY_VIEW
WHERE MEMBER_CASUAL = 'member' AND YEAR_REPORT >= '2020'
GROUP BY YEAR_REPORT, MEMBER_CASUAL, RIDE_MORE_45_MINUTES, RIDEABLE_TYPE ORDER BY YEAR_REPORT, MEMBER_CASUAL,RIDE_MORE_45_MINUTES, RIDEABLE_TYPE