/**** CREATING THE DB ****/

-- CREATING THE DATABASE
CREATE DATABASE DIVVY_DB
GO

-- INCREASING THE SIZE

ALTER DATABASE DIVVY_DB
MODIFY FILE
    (NAME = DIVVY_DB,
    SIZE = 1024MB);
GO

ALTER DATABASE DIVVY_DB
MODIFY FILE
    (NAME = DIVVY_DB,
    SIZE = 7160MB);
GO

ALTER DATABASE DIVVY_DB
MODIFY FILE
    (NAME = DIVVY_DB,
    SIZE = 10240MB);
GO

